const remindersActionTypes = {
  GET_REMINDER_DETAILS: 'GET_REMINDER_DETAILS',
  ADD_NEW_REMINDER: 'ADD_NEW_REMINDER',
  MARK_REMINDER_AS_COMPLETE: 'MARK_REMINDER_AS_COMPLETE',
  EDIT_REMINDER: 'EDIT_REMINDER',
  DELETE_REMINDER: 'DELETE_REMINDER',
  MARK_REMINDER_AS_MISSED: 'MARK_REMINDER_AS_MISSED',
};

export default remindersActionTypes;
