const goalsActionTypes = {
  ADD_NEW_GOAL: 'ADD_NEW_GOAL',
  GET_ALL_GOALS: 'GET_ALL_GOALS',
  DELETE_GOAL: 'DELETE_GOAL',
  MARK_GOAL_AS_COMPLETE: 'MARK_GOAL_AS_COMPLETE',
  RESTART_GOAL: 'RESTART_GOAL',
  GOAL_REACHED: 'GOAL_REACHED',
};

export default goalsActionTypes;
