import { StyleSheet } from 'react-native';
import { Colors } from './Colors';

const Styles = StyleSheet.create({
  submitContainer: {
    padding: 25,
    flex: 1,
    alignItems: 'center',
  },
  submitButton: {
    backgroundColor: Colors.TEXT,
    borderRadius: 25,
    shadowColor: Colors.PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 15,
    borderWidth: 2,
    borderColor: Colors.PRIMARY_COLOR,
    fontSize: 20,
    height: 50,
    flex: 1,
    flexDirection: 'row',
    width: 135,
  },

  markAsCompleteButton: {
    backgroundColor: Colors.TEXT,
    borderRadius: 25,
    shadowColor: Colors.PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 15,
    borderWidth: 2,
    borderColor: Colors.PRIMARY_COLOR,
    fontSize: 20,
    height: 50,
    flex: 1,
    flexDirection: 'row',
    width: 275,
  },
  submitIconContainer: {
    justifyContent: 'center',
    alignContent: 'flex-start',
  },
  submitIconStyle: {
    color: Colors.PRIMARY_COLOR,
    left: 20,
    fontSize: 25,
  },
  submitText: {
    fontStyle: 'normal',
    fontSize: 25,
    color: Colors.PRIMARY_COLOR,
    fontWeight: 'normal',
    left: 30,
  },
  container: {
    padding: 25,
    paddingBottom: 0,
    flex: 1,
  },
  button: {
    backgroundColor: Colors.TEXT,
    borderRadius: 5,
    shadowColor: Colors.PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 8,
    borderWidth: 2,
    borderColor: Colors.PRIMARY_COLOR,
    fontSize: 20,
    height: 50,
    flex: 1,
    flexDirection: 'row',
  },
  iconContainer: {
    justifyContent: 'center',
    alignContent: 'flex-start',
  },
  icon: {
    color: Colors.PRIMARY_COLOR,
    left: 25,
    fontSize: 25,
  },
  text: {
    fontStyle: 'normal',
    fontSize: 25,
    color: Colors.PRIMARY_COLOR,
    fontWeight: 'normal',
    left: 40,
  },
  editButtonContainer: {
    padding: 20,
    paddingBottom: 0,
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  editButton: {
    backgroundColor: Colors.PRIMARY_COLOR,
    borderRadius: 25,
    shadowColor: Colors.PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 12,
    borderWidth: 2,
    borderColor: Colors.PRIMARY_COLOR,
    fontSize: 20,
    height: 50,
    flex: 1,
    color: Colors.PRIMARY_COLOR,
    flexDirection: 'row',
    width: 120,
  },
  editButtonIconContainer: {
    justifyContent: 'center',
    alignContent: 'flex-end',
  },
  editButtonIcon: {
    color: Colors.TEXT,
    left: 18,
    fontSize: 25,
  },
  editButtonText: {
    fontStyle: 'normal',
    fontSize: 25,
    color: Colors.TEXT,
    fontWeight: 'normal',
    left: 28,
  },

  missedButtonSubmitContainer: {
    paddingTop: 0,
    padding: 25,
    flex: 1,
    alignItems: 'center',
  },
  missedButton: {
    paddingTop: 0,
    backgroundColor: Colors.PRIMARY_COLOR,
    borderRadius: 25,
    shadowColor: Colors.PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 8,
    borderWidth: 2,
    borderColor: Colors.PRIMARY_COLOR,
    fontSize: 20,
    height: 50,
    flex: 1,
    flexDirection: 'row',
    color: Colors.PRIMARY_COLOR,
    width: 300,
  },
  missedButtonText: {
    fontStyle: 'normal',
    fontSize: 25,
    color: Colors.TEXT,
    fontWeight: 'normal',
    left: 30,
  },
});

export default Styles;
