require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'remind' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'remindTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'remind-tvOS' do
  # Pods for remind-tvOS

  target 'remind-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
